#!/usr/bin/env sh

# here copy the jenkinsmonitor.properties.template to ~/jenkinsmonitor.properties if not exists
if [ -f ~/jenkinsmonitor.properties ]
then
  echo "~/jenkinsmonitor.properties exists"
else
  cp jenkinsmonitor.properties.template ~/jenkinsmonitor.properties
fi

# start the app
ls -Flarc
java -jar jenkinsmonitor-jar-with-dependencies.jar

