#!/usr/bin/env sh

# here copy the jenkinsmonitor.properties.template to ~/jenkinsmonitor.properties if not exists
if [ -f ~/jenkinsmonitor.properties ]
then
  echo "~/jenkinsmonitor.properties exists"
else
  cp ./jenkinsmonitor.properties.template ~/jenkinsmonitor.properties
fi

# start the app
ls ./usr/
./usr/bin/java -jar ./usr/share/jenkinsmonitor/jenkinsmonitor-jar-with-dependencies.jar

