#!/usr/bin/sh

# here copy the jenkinsmonitor.properties.template to ~/jenkinsmonitor.properties if not exists
if [ -f ~/jenkinsmonitor.properties ]
then
  echo "~/jenkinsmonitor.properties exists"
else
  cp $APPDIR/jenkinsmonitor.properties.template ~/jenkinsmonitor.properties
fi

# start the app
echo "### AppRun"
$APPDIR/usr/bin/java -jar $APPDIR/usr/bin/jenkinsmonitor-jar-with-dependencies.jar

